site_name: HCI Docs
theme: material
pages:
  - Home: index.md
  - Design Ethnography: design-ethnography.md
  - Studying Human Performance: studying-human-performance.md
  - Cognitive Ergonomics in Design: cognitive-ergonomics-in-design.md
  - Simulation and Digital Human Modeling: simulation-and-digital-human-modeling.md
