site_name: HCI Docs
theme: material
pages:
  - Home: index.md
  - Simulation and Digital Human Modeling: SDHM-course.md
  - Studying Human Performance: SHP-course.md
  - Cognitive Ergonomics in Design: CEID-course.md
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
